language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack: 
  email:
  - ademo@126.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: 1bdeWzN9hUmuDELkM9GpVf+VwnSmjjlGtLKHZ+AftlaHekdNSEgwAKNMJ5AHMGT22fquJoR8qx7adoEoHG/KDfSx10BNOnt4Yn9z2ETwBXG/+xP5oR+MowMfLb+QXz+egbfS/1jKechnLWsEoqbIIaxfmjniZkWkQHgN+6sNOYWRl6d8Uz9u6yKxjK8LSWu/SAkA/zapLdrhjEJXSSPnXdFlH/Cu+Akd/S70UToSyNs8Uu7b+tSd0pU2i8quzvSllNxGzz4yOOB8wEzrfOIed4EouCIuF1m6myYTYgCD3k4I6ipMG040Qah5iTc2tD5hbFFHXq6/H3lpCtBVEKuTXqF+/jVKSKmJE+N111N6Ue4d1R6f/LRfZcgDWnXpw+TDI3h1neHQjGcfbcLDl/4efmhalXo0LQvkvFmdcVHVBc6ryfjL1Z9wUNoXNzSOIAlIsEDzDdlqRzGPqu2B4yoPzmmTk7Eo/XhSI7FwXWICdoBWLlRna5Mc7pe2lGQqZrcQU4dWtipi1qlF0RlT1HIztGg8yqJszrwuARd2LuVmK6NyGOUMjtrBWFHn1giFCpTsvBU/m+m4bFx/pjaIk0LNZWcNmag3meHlLoF2eQKvJL4HLa+tmDyI8ObBYHHsCt7Ga0N9imApLkiQLZ+LBMSL+TH/mjPj4dVrFfOENke+ekE=
  - secure: VduzPD68XVcyVwU6A1cJoiOuOFGz3qCqU94MCS9XJAmfjr8mNsNho33CI9WcIwigEN0caWj1JPVPrU3WvmZEpzFNwx3mIPEp3xmmwy7tuPQYO4M5zhQ4hlkgC6LGu0ncGRu3cQoc8+7E0oEqQ7Ad5PJ3vYHaewViOCyoByJSqLQvzSBzk7aLVtd75jg8a8564KmgnlguwwqxbK9TEatahtw3akhic1jNCsXA7AYmgS5VKaajtCPpmITeuVcuIaoIH3BfYl+LKKga6G3UfICkvzJnLZJ7DGgE7q6CIsY3qVTDfM+orhTFv8buUG/UBAYU0CU7k8mOXbGGxsenReA7NZxH1qm+Xqs0bSsztMbozXpVI0mcwIdHHUy4kBUhrDgGXaM/EduWjfwTRtFZ45eVW9ijc/H5fpVP+j003rNISnQnS3F8jQ2gkwJKEwxD5SDEuZbxas886HaKzVmf7lrGt36zHEfiHKXBMuQHQY98IpMm4t4QlGSZ4k91I6D1In8JdeTnmmdlJVS4JW6mK/I5gBqGwwqJr83p6/dvpnyWK9RTBvCDdxnz3h1X+WmrGoIZ+zc0o1f8SCFJd4Q1v/0P5QMgGKpOfJ416IZ7kUOHKg4byETJcwwgFd/ThqLdOXASqjAi6JfyahX3mynoSEQDF2Y4381Bc7Yu9LrhRAJvKCI=
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push ademo/tmx-licensing-service:chapter8
- docker push ademo/tmx-organization-service:chapter8
- docker push ademo/tmx-confsvr:chapter8
- docker push ademo/tmx-eurekasvr:chapter8
- docker push ademo/tmx-zuulsvr:chapter8
